### ISSUE TITLE
How to add a label to update

### ISSUE THREAD

**Issue by heshanlk** [comyarzaheri/Chronos-Swift#7]
I can't get a label counter working with this lib, how to set it up?. I have a separate function which does the label update with NSTimer I used 

    func fireProgress(timer: NSTimer) {
        self.valueLabel.text = self.timeRemaining
    }

how can I do the same with this lib?

**Comment by comyarzaheri** [comment]
I wrote this off the top of my head so it may not work, but something like this is probably what you're looking for. Feel free to reopen this issue if you run into any more problems.

```swift
// Setup
let label = UILabel() // Label we'll update
var remaining: Double = 10.0 // Total time remaining
let interval: Double = 1.0 // We want the timer to fire once a second

// Timer
let dispatchTimer = DispatchTimer(interval: interval, closure: { (timer: RepeatingTimer, invocations: Int) in
            // Ensure we update label on main queue
            dispatch_async(dispatch_get_main_queue()) {
                remaining -= interval
                label.text = "\(remaining)"
                if (remaining <= 0.0) {
                    timer.stop()
                }
            }
    })

// Starts the timer. Waits the provided interval time before firing the first time
dispatchTimer.start(false)
```

**Comment by heshanlk** [comment]
Thanks a lot, I'll give it a try
